version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/music_communication_app
      - gem_data:/usr/local/bundle
    ports:
      - "3001:3001"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

volumes:
  gem_data:
  redis:
